#!/usr/bin/env bash

### BASH BASE [V2] BEGIN ###

if [ -n "${BASH_VERSINFO[*]}" ]; then
  if [ "${BASH_VERSINFO[0]}" -ge 4 ] && [ "${BASH_VERSINFO[1]}" -ge 4 ]; then
    :
  elif [ "${BASH_VERSINFO[0]}" -ge 5 ]; then
    :
  else
    exit 1
  fi
else
  exit 1
fi

if [ "${SCRIPT_DEBUG}" = 'true' ]; then
  echo 'Script debugging is enabled, allowing bash commands and their arguments to be printed as they are executed.'
  set -x
fi

# Notes:
#   - https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
#   - https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html
#   - https://en.wikipedia.org/wiki/Umask
#
BASH_COMPAT=44
export BASH_COMPAT
set -e -o pipefail
shopt -s dotglob extglob
umask "${UMASK:-0007}"

### BASH BASE [V2] END ###

case "$(uname)" in
  Darwin*)
    ;;
  *)
    echo 'Sorry, only macOS is supported at this moment...'
    exit 1
    ;;
esac

# shellcheck source=functions.conf
# . "$(dirname "${0}")"/functions.conf

# trap '_catch_all ${?}' ERR SIGHUP SIGINT SIGQUIT SIGTERM

# shellcheck disable=SC2048
# shellcheck disable=SC2086
"$(brew --prefix 2> /dev/null)"/bin/shellcheck -P SCRIPTDIR -x ${*}

# _exit 0
