#!/usr/bin/env bash

# shellcheck source=bash44.conf
. "$(dirname "${0}")"/bash44.conf || exit 1
# shellcheck source=constants.conf
. "$(dirname "${0}")"/constants.conf
# shellcheck source=functions.conf
. "$(dirname "${0}")"/functions.conf

case "$(uname)" in
  Darwin*) ;;
  *)
    _exit 1 'Sorry, only macOS is supported at this moment, exiting.'
    ;;
esac

# trap '_catch_all ${?}' ERR SIGHUP SIGINT SIGQUIT SIGTERM

# shellcheck disable=SC2048
# shellcheck disable=SC2086
"${HOMEBREW_ROOT:-"$(brew --prefix 2> /dev/null)"}"/bin/shfmt --case-indent --indent 2 --space-redirects ${*}
