#!/usr/bin/env bash

# shellcheck source=bash44.conf
. "$(dirname "${0}")"/bash44.conf || exit 1
# shellcheck source=functions.conf
. "$(dirname "${0}")"/functions.conf

_help() {
  local exit_code
  exit_code="${1:-1}"
  cat << EOT

  Usage: $(basename "${0}") [OPTION...] FILE

  Help options:
    -H Show this help message
    -U Display brief usage
    -V Print version

EOT
  exit "${exit_code}"
}

trap '_catch_all ${?}' ERR SIGHUP SIGINT SIGQUIT SIGTERM

OPTIND=1
while getopts 'HUV' ARGS; do
  case "${ARGS}" in
    H | U)
      _help 0
      ;;
    V)
      _exit 0 'v3'
      ;;
    ?)
      _help 1
      ;;
  esac
done
shift $((OPTIND - 1))

[ $# -ge 1 ] || _help 1

if [ -r "${1:?}" ]; then
  perl -e 's/\r\n|\n|\r/\r\n/g' -p "${1:?}"
else
  _exit 1 "'${1:?}' was NOT readable, exiting."
fi
