#!/usr/bin/env bash

# shellcheck source=bash44.conf
. "$(dirname "${0}")"/bash44.conf || exit 1
# shellcheck source=functions.conf
. "$(dirname "${0}")"/functions.conf

case "$(uname)" in
  Darwin*) ;;
  *)
    _exit 1 'Sorry, only macOS is supported at this moment, exiting.'
    ;;
esac

# Notes:
#   - https://github.com/romkatv/powerlevel10k
#
_download_and_install() {
  git clone --depth 1 https://github.com/romkatv/powerlevel10k.git --quiet "${HOME:?}"/.powerlevel10k
  pushd "${HOME:?}"/.powerlevel10k
  # shellcheck disable=SC2038
  find config -name "*.zsh" -type f 2> /dev/null |
    xargs sed -i '' 's/branch > 32/branch > 64/g'
  git gc --quiet
  popd
}

_help() {
  local exit_code
  exit_code="${1:-1}"
  cat << EOT

  Usage: $(basename "${0}") [OPTION...]

  Options:
    -f Force

  Help options:
    -H Show this help message
    -U Display brief usage
    -V Print version

EOT
  exit "${exit_code}"
}

trap '_catch_all ${?}' ERR SIGHUP SIGINT SIGQUIT SIGTERM

OPTIND=1
while getopts 'fHUV' ARGS; do
  case "${ARGS}" in
    f)
      force='true'
      ;;
    H | U)
      _help 0
      ;;
    V)
      _exit 0 'v3'
      ;;
    ?)
      _help 1
      ;;
  esac
done
shift $((OPTIND - 1))

if [ -d "${HOME:?}"/.powerlevel10k ]; then
  if [ "${force}" = 'true' ]; then
    rm -f -r -v "${HOME:?}"/.powerlevel10k
    _download_and_install
  fi
else
  _download_and_install
fi
