#!/usr/bin/env bash

# shellcheck source=bash44.conf
. "$(dirname "${0}")"/bash44.conf || exit 1
# shellcheck source=constants.conf
. "$(dirname "${0}")"/constants.conf
# shellcheck source=functions.conf
. "$(dirname "${0}")"/functions.conf

case "$(uname)" in
  Darwin*) ;;
  *)
    _exit 1 'Sorry, only macOS is supported at this moment, exiting.'
    ;;
esac

# Notes:
#   - https://mirror.openshift.com/pub/openshift-v4/clients/ocp/
#
_download_and_install() {
  case "$(uname -m)" in
    arm64)
      # shellcheck disable=SC2086
      curl ${CURL_OPTIONS} https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-mac-arm64.tar.gz 2> /dev/null |
        tar fxz - --directory "${HOME:?}"/.bin oc && codesign --sign '-' "${HOME:?}"/.bin/oc
      ;;
    x86_64)
      # shellcheck disable=SC2086
      curl ${CURL_OPTIONS} https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-mac.tar.gz 2> /dev/null |
        tar fxz - --directory "${HOME:?}"/.bin oc
      ;;
    *)
      _exit 1 'unsupported machine hardware, exiting.'
      ;;
  esac
}

_help() {
  local exit_code
  exit_code="${1:-1}"
  cat << EOT

  Usage: $(basename "${0}") [OPTION...]

  Options:
    -f Force

  Help options:
    -H Show this help message
    -U Display brief usage
    -V Print version

EOT
  exit "${exit_code}"
}

trap '_catch_all ${?}' ERR SIGHUP SIGINT SIGQUIT SIGTERM

OPTIND=1
while getopts 'fHUV' ARGS; do
  case "${ARGS}" in
    f)
      force='true'
      ;;
    H | U)
      _help 0
      ;;
    V)
      _exit 0 'v3'
      ;;
    ?)
      _help 1
      ;;
  esac
done
shift $((OPTIND - 1))

if [ -f "${HOME:?}"/.bin/oc ]; then
  if [ "${force}" = 'true' ]; then
    rm -f -v "${HOME:?}"/.bin/oc
    _download_and_install
  fi
else
  _download_and_install
fi
# completion
#
rm -f "${HOME:?}"/.local/share/zsh/site-functions/_oc
if [ -x "${HOME:?}"/.bin/oc ]; then
  {
    echo '#compdef kubectl oc'
    echo '__kubectl_debug() { : }'
    "${HOME:?}"/.bin/oc completion zsh | sed -e '/#compdef .*/d'
  } >> "${HOME:?}"/.local/share/zsh/site-functions/_oc
fi
